version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: this_coder
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
  redis:
    image: "redis/redis-stack-server"
    container_name: "redis"
    ports:
      - "6379:6379"
      - "8001:8001"

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.dev
  #   container_name: "server"
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - ./server/.env
  #   environment:
  #     - NODE_ENV=development
  #     - MONGO_URI=mongodb://this_code:password@mongodb
  #     - REDIS_URI=redis://redis
  #   depends_on:
  #     - mongodb
  #     - redis
  #   develop:
  #     watch:
  #       - path: ./server/package*.json
  #         action: rebuild
  #       - path: ./server
  #         target: /app
  #         action: sync

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   container_name: "client"
  #   ports:
  #     - "5173:5173"
  #   env_file:
  #     - ./client/.env
  #   depends_on:
  #     - server
  #   develop:
  #     watch:
  #       - path: ./client/package*.json
  #         action: rebuild
  #       - path: ./client
  #         target: /app
  #         action: sync

volumes:
  mongodb_data:
    driver: local
